Billenium2/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views #logowanie
app_name = 'polls'

urlpatterns = [
    path('',views.index,name='index'),
    path('PersonList/', views.PersonList.as_view(), name='personList'),
    path('DetailPerson/<int:pk>/', views.DetailPerson.as_view(), name='detailPerson'),
    # ex: /polls/5/results/
   # path('detailProject/<int:idProject>/', views.detailProject, name='detailProject'),
    # ex: /polls/5/vote/
   # path('detailNotification/<int:idNotification>/', views.detailNotification, name='detailNotification'),
    path('PersonFormExecute/', views.personFormExecute, name='personFormExecute'),
    path('PersonFormDeleteExecute/', views.personFormDeleteExecute, name='personDelee'),
    path('AddPersonFormExecute/', views.addPersonFormExecute, name='personAdd'),

    path('ProjectList/', views.ProjectList.as_view(), name='projectList'),

    #url(r'^register/$', views.register, name='register'),
    #url(r'^login/$', auth_views.LoginView, name='login'),
    #url(r'^logout/$', auth_views.auth_logout, name='logout'),


    path('login/', views.login_handmade, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('Register/', views.register, name='register'),
]

polls/models.py
from django.db import models

# Create your models here.
from django.db.models.functions import datetime
from django.forms import forms


from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# class Person(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     #idPerson = models.AutoField(primary_key=True)
#     position = models.CharField(max_length=60)
#     admin = models.BooleanField(default=False)

class Person2(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #idPerson = models.AutoField(primary_key=True)
    position = models.CharField(max_length=60)
    admin = models.BooleanField(default=False)


class Project(models.Model):
    idProject = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    owner = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    state = models.CharField(max_length=50)





class Notification(models.Model):
    idNotification = models.AutoField(primary_key=True)
    who = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    what = models.CharField(max_length=100)
    projectOwner = models.ForeignKey(Project,on_delete=models.CASCADE)

polls/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from polls import models
from django.contrib.auth.models import User

from polls.models import Person2 as Person


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'last_name','first_name','email')


class UserProfileInfoForm(forms.ModelForm):
    position = forms.CharField(max_length=30, required=False, help_text='Optional.')
    admin = forms.BooleanField(required=False, help_text='Optional.')
    class Meta():
        model = Person
        fields = ('position', 'admin')

polls/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext
from django.urls import reverse
from django.views import generic

from .models import Person2 as Person,Project,Notification

#logowanie
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.http import JsonResponse
from .forms import SignUpForm, UserProfileInfoForm
from django.contrib.auth import authenticate

# Create your views here.

class PersonList(generic.ListView):
    template_name = 'polls/person.html'
    context_object_name = 'person'

    def get_queryset(self):
        return Person.objects.order_by('user')



def index (request):
    return HttpResponse("Hello, world. You're at the polls index.")



class  DetailPerson(generic.DetailView):
    template_name = 'polls/detailPerson.html'
    context_object_name = 'person'

    def get_queryset(self):
        return Person.objects.order_by('idPerson')
    #person = Person.objects.filter(idPerson=pk).first()



    #person2 = get_object_or_404(Person, idPerson=idPerson)





def personFormExecute(request):
    try:
        person2 = get_object_or_404(Person, id=request.POST['id'])
        person2.user.first_name = request.POST['fname']
        person2.user.last_name = request.POST['lname']
        person2.user.username = request.POST['login']
        try:
            if request.POST['password']:
                person2.user.set_password(request.POST['password'])
        finally:
            ex = "nie zmieniono hasła"

        #person2.password = request.POST['password']
        person2.position = request.POST['position']
        #pom = False
        try:
            if (request.POST['czyA']):
                pom = True
        except:
            pom = False
        person2.admin = pom

    except (KeyError, Person):
        # Redisplay the question voting form.
        return render(request, 'polls/detailPerson.html', {
            'person': person2,
            'error_message': "You didn't select a choice.",
        })
    else:
        person2.user.save()
        person2.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:detailPerson', args=(person2.id,)))


def personFormDeleteExecute(request):
    try:
        person2 = get_object_or_404(Person, id=request.POST['id'])

    except (KeyError, Person):
        # Redisplay the question voting form.
        return render(request, 'polls/detailPerson.html', {
            'person': person2,
            'error_message': "You didn't select a choice.",
        })
    else:

        person2.delete()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:personList'))

def addPersonFormExecute(request):
    #pom = False
    try:
        if (request.POST['czyA']):
             pom = True
    except:
        pom = False

    person2 = Person()
    #person = Person(firstName=request.POST['fname'], lastName=request.POST['lname'], login = request.POST['login'], password=request.POST['password'], position=request.POST['position'], admin= pom)

    person2.firstName = request.POST['fname']
    person2.lastName = request.POST['lname']
    person2.login = request.POST['login']
    person2.password = request.POST['password']
    person2.position = request.POST['position']
    person2.admin = pom

    person2.save()
    return HttpResponseRedirect(reverse('polls:personList'))


def detailProject(request, idProject):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % idProject)

def detailNotification(request, idNotification):
    return HttpResponse("You're voting on question %s." % idNotification)




class ProjectList(generic.ListView):
    template_name = 'polls/ProjectList.html'
    context_object_name = 'project'

    def get_queryset(self):
        return Project.objects.order_by('idProject')





def register(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    else:
        registered = False
        if request.method == 'POST':
            user_form = SignUpForm(data=request.POST)
            profile_form = UserProfileInfoForm(data=request.POST)
            if user_form.is_valid() and profile_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form.errors,profile_form.errors)
        else:
            user_form = SignUpForm()
            profile_form = UserProfileInfoForm()
        return render(request,'polls/register.html',
                              {'user_form':user_form,
                               'profile_form':profile_form,
                               'registered':registered})

def login_handmade(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)

    er = []

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # Redirect to a success page.
                return render(request,'polls/person.html')
            else:
                # Return a 'disabled account' error message
                #er.append("Twoje konto jest zablokowane")
                return render(request,'polls/login.html')
        else:
            # Return an 'invalid login' error message.
            #er.append("Bledne logowanie")
            return render(request, 'polls/login.html')

    return render(request,'polls/login.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:login'))

polls/templates/polls/ProjectList.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
  <tr>
      <th>Id</th>
      <th>Nazwa</th>
      <th>Opis</th>
      <th>Project owner</th>
      <th>Status</th>
  </tr>

{% if person %}
    <tr>
    {% for p in project %}

         <td>{{ p.name }}</td>
         <td>{{ p.description }}</td>
         <td>{{ p.owner }}</td>
         <td>{{ p.state }}</td>
         </tr>
    {% endfor %}

{% else %}
    <p>No polls are available.</p>
{% endif %}
</table>

<a href="{% url 'polls:addPerson' %}" ><button>Add</button></a>

</body>
</html>

polls/templates/polls/addPerson.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ person.fitstName }} {{ person.LastName }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:addPerson' %}" method="post">
{% csrf_token %}
    <input type="text" id="id" name="id" style="display: none" ><br>
    <label for="fname">Imie:</label><br>
    <input type="text" id="fname" name="fname" ><br>
    <label for="lname">Nazwisko</label><br>
    <input type="text" id="lname" name="lname" ><br>
    <label for="login">Login</label><br>
    <input type="text" id="login" name="login" ><br>
    <label for="password">Password</label><br>
    <input type="password" id="password" name="password" ><br>
    <label for="email">Password</label><br>
    <input type="email" id="email" name="email" ><br>
    <label for="position">Stanowisko</label><br>
    <input type="text" id="position" name="position" v><br>
    <label for="czyA">Admin</label>
    <input type="checkbox" id="czyA" name="czyA" ><br><br>
    <input type="submit" value="Add">
</form>

</body>
</html>

polls/templates/polls/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'polls:index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'polls:register' %}">addPerson</a></li>
          <li><a class="navbar-link" href="{% url 'polls:personList' %}">PersonList</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'polls:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'polls:login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

polls/templates/polls/detailPerson.html
{% extends "polls/base.html" %}
{#  load staticfiles %}#}
{% block body_block %}
<h1>{{ person.user.first_name}} {{person.user.last_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:personFormExecute' %}" method="post">
{% csrf_token %}
    <input type="text" id="id" name="id" style="display: none" value="{{ person.id }}"><br>
    <label for="fname">Imie:</label><br>
    <input type="text" id="fname" name="fname" value="{{ person.user.first_name }}"><br>
    <label for="lname">Nazwisko</label><br>
    <input type="text" id="lname" name="lname" value="{{  person.user.last_name }}"><br>
    <label for="login">Login</label><br>
    <input type="text" id="login" name="login" value="{{ person.user.username}}"><br>
    <label for="password">Password</label><br>
    <input type="password" id="password" name="password" value=""><br>
    <label for="position">Stanowisko</label><br>
    <input type="text" id="position" name="position" value="{{ person.position }}"><br>
    <label for="czyA">Admin</label>
    <input type="checkbox" id="czyA" name="czyA" {% if person.admin %} checked {% endif %}><br><br>
    <input type="submit" value="Update">
</form>


<form action="{% url 'polls:personDelee' %}" method="post">
{% csrf_token %}
     <input type="text" id="id" name="id" style="display: none" value="{{ person.id }}">
    <input type="submit" value="Delete">
</form>
{% endblock %}

polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="content">
<form action="{% url 'polls:login' %}" method="post">
{% csrf_token %}

    <label for="username">Login</label><br>
    <input type="text" id="login" name="username" ><br>
    <label for="password">Password</label><br>
    <input type="password" id="password" name="password" ><br>
    <label for="position">Stanowisko</label><br>
    <input type="submit" value="login">
</form>
</div>

</body>
</html>

polls/templates/polls/person.html
{% extends "polls/base.html" %}
{#  load staticfiles %}#}
{% block body_block %}
<table>
  <tr>
      <th>Id</th>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Login</th>
      <th>Stanowisko</th>
      <th>Admin</th>
      <th>Wyświetl</th>
  </tr>
{#  admin, id, position, user, user_id #}
{% if person.count > 0  %}
    <tr>
    {% for p in person %}
         <td>{{ p.id }}</td>
         <td>{{ p.user.first_name }}</td>
         <td>{{ p.user.last_name }}</td>
         <td>{{ p.user.username }}</td>
         <td>{{ p.position }}</td>
         <td>{{ p.admin }}</td>
        <td><a href="{% url 'polls:detailPerson'  p.id %}"><button value="Wyswietl">Wyswietl</button> </a></td></tr>
    {% endfor %}

{% else %}
    <p>No polls are available.</p>
{% endif %}
</table>
<a href="{% url 'polls:register' %}" ><button>Add</button></a>

{% endblock %}

polls/templates/polls/register.html
{% extends "polls/base.html" %}
{#  load staticfiles %}#}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" action="{% url 'polls:register' %}" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}